### ISSUE TITLE
Add table widget

### ISSUE THREAD

**Issue by juhamust** [SC5/mozaik-ext-sheets#7]
While list can be styled, often the alignment is wanted - where table fits nicely.

**Comment by robbyking3** [comment]
in mine I edited the `index.styl` to make the `li`s `display:flex` then the child spans `flex: 1; border: 1px solid #fff;` 

made it somewhat table-like

**Comment by juhamust** [comment]
Good point. Have to consider that.

**Comment by juhamust** [comment]
Implemented in 3c8ea99a8. Thanks for the tip, @robbyking3 !
